language: c

os:
  - linux
  - freebsd
  - osx

jobs:
  include:
    -
      os: linux
      dist: focal

arch:
  - s390x
  - amd64

compiler:
  - gcc

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install build-essential curl; fi
  - cd "$TRAVIS_BUILD_DIR"
  - $CC -dM -E - < /dev/null
  - make test

install: skip
