language: c
dist: focal

os:
  - linux

arch:
  - s390x
  - amd64

compiler:
  - gcc

script:
  - sudo apt-get install build-essential curl
  - cd "$TRAVIS_BUILD_DIR"
  - $CC -dM -E - < /dev/null
  - make test

install: skip
