language: c

os:
  - linux

arch:
  - s390x
  - amd64

compiler:
  - gcc

script:
  - sudo apt-get install build-essential curl
  - cd "$TRAVIS_BUILD_DIR"
  - sh nobearssl.sh
  - make test

install: skip
