language: c

os:
  - linux

arch:
  - s390x
  - amd64

compiler:
  - gcc

script:
  - sudo apt-get install build-essential curl
  - cd "$TRAVIS_BUILD_DIR"
  - $CC -dM -E - < /dev/null
  - sh bearssl.sh
  - ( cd bearssl; make; rm build/*.so; )
  - sudo make test

install: skip
