language: c

jobs:
  include:
    -
      os: linux
      dist: focal
      arch: amd64
      addons:
        apt:
          packages:
            - build-essential
            - curl
    -
      os: linux
      dist: focal
      arch: s390x
      addons:
        apt:
          packages:
            - build-essential
            - curl
    -
      os: osx
# TODO
#    -
#      os: freebsd
#      addons:
#        pkg:
#          - curl

script:
  - cd "$TRAVIS_BUILD_DIR"
  - $CC -dM -E - < /dev/null
  - make test

install: skip
