escape: info: start 
\r\n\r\n\0\r\nQUIT\n!!\0$\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0OK\n\n
escape: info: start 
PROXY UNKNOWN\r\nOK\n\n
escape: info: start 
\r\n\r\n\0\r\nQUIT\n!\x11\0\x0c\x01\x02\x03\x04\x01\x02\x03\x04\x04\xd2\x04\xd2OK\n\n
escape: info: start 
PROXY TCP4 1.2.3.4 1.2.3.4 1234 1234\r\nOK\n\n
escape: info: start 
\r\n\r\n\0\r\nQUIT\n!!\0$\xab\xcd\xab\xcd\xab\xcd\xab\xcd\xab\xcd\xab\xcd\xab\xcd\xab\xcd\xab\xcd\xab\xcd\xab\xcd\xab\xcd\xab\xcd\xab\xcd\xab\xcd\xab\xcd\x04\xd2\x04\xd2OK\n\n
escape: info: start 
PROXY TCP6 abcd:abcd:abcd:abcd:abcd:abcd:abcd:abcd abcd:abcd:abcd:abcd:abcd:abcd:abcd:abcd 1234 1234\r\nOK\n\n
escape: info: start 
\r\n\r\n\0\r\nQUIT\n!!\0$\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0OK\n\n
escape: info: start 
PROXY UNKNOWN\r\nOK\n\n
escape: info: start 
\r\n\r\n\0\r\nQUIT\n!!\0$\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xffOK\n\n
escape: info: start 
PROXY TCP6 ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff 65535 65535\r\nOK\n\n
escape: info: start 
\r\n\r\n\0\r\nQUIT\n!!\0$\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xffOK\n\n
escape: info: start 
PROXY TCP6 ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff 65535 65535\r\nOK\n\n
escape: info: start 
\r\n\r\n\0\r\nQUIT\n!\x11\0\x0c\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xffOK\n\n
escape: info: start 
PROXY TCP4 255.255.255.255 255.255.255.255 65535 65535\r\nOK\n\n
tlswrapper: error: unable to parse proxy-protocol string 'PROXY\r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse proxy-protocol string 'PROXY TCP6\r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse remoteip from proxy-protocol string 'PROXY TCP4 \r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse remoteip from proxy-protocol string 'PROXY TCP4 2\r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse remoteip from proxy-protocol string 'PROXY TCP4 255\r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse remoteip from proxy-protocol string 'PROXY TCP4 255.\r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse remoteip from proxy-protocol string 'PROXY TCP4 255.255.255.255\r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse localip from proxy-protocol string 'PROXY TCP4 255.255.255.255 \r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse localip from proxy-protocol string 'PROXY TCP4 255.255.255.255 255.255.255.255\r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse repoteport from proxy-protocol string 'PROXY TCP4 255.255.255.255 255.255.255.255 \r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse repoteport from proxy-protocol string 'PROXY TCP4 255.255.255.255 255.255.255.255 65535\r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse localport from proxy-protocol string 'PROXY TCP4 255.255.255.255 255.255.255.255 65535 \r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse remoteip from proxy-protocol string 'PROXY TCP4 255.255.256.255 255.255.255.255 65535 \r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse remoteip from proxy-protocol string 'PROXY TCP4 255.256.255.255 255.255.255.255 65535 65535\r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse localip from proxy-protocol string 'PROXY TCP4 255.255.255.255 255.256.255.255 65535 65535\r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse repoteport from proxy-protocol string 'PROXY TCP4 255.255.255.255 255.255.255.255 65536 65535\r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
tlswrapper: error: unable to parse localport from proxy-protocol string 'PROXY TCP4 255.255.255.255 255.255.255.255 65535 65536\r\n' 
tlswrapper: fatal: unable to receive incoming proxy-protocol v1 string 
