tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-prime256v1-ec-prime256v1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-prime256v1-ec-prime256v1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-prime256v1-ec-secp384r1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-prime256v1-ec-secp384r1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-prime256v1-ec-secp521r1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-prime256v1-ec-secp521r1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-prime256v1-rsa-2048-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-prime256v1-rsa-2048-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-prime256v1-rsa-3072-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-prime256v1-rsa-3072-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-prime256v1-rsa-4096-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-prime256v1-rsa-4096-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-secp384r1-ec-prime256v1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-secp384r1-ec-prime256v1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-secp384r1-ec-secp384r1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-secp384r1-ec-secp384r1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-secp384r1-ec-secp521r1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-secp384r1-ec-secp521r1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-secp384r1-rsa-2048-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-secp384r1-rsa-2048-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-secp384r1-rsa-3072-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-secp384r1-rsa-3072-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-secp384r1-rsa-4096-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-secp384r1-rsa-4096-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-secp521r1-ec-prime256v1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-secp521r1-ec-prime256v1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-secp521r1-ec-secp384r1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-secp521r1-ec-secp384r1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-secp521r1-ec-secp521r1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-secp521r1-ec-secp521r1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-secp521r1-rsa-2048-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-secp521r1-rsa-2048-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-secp521r1-rsa-3072-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-secp521r1-rsa-3072-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-ec-secp521r1-rsa-4096-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-ec-secp521r1-rsa-4096-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-2048-ec-prime256v1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-2048-ec-prime256v1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-2048-ec-secp384r1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-2048-ec-secp384r1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-2048-ec-secp521r1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-2048-ec-secp521r1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-2048-rsa-2048-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-2048-rsa-2048-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-2048-rsa-3072-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-2048-rsa-3072-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-2048-rsa-4096-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-2048-rsa-4096-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-3072-ec-prime256v1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-3072-ec-prime256v1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-3072-ec-secp384r1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-3072-ec-secp384r1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-3072-ec-secp521r1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-3072-ec-secp521r1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-3072-rsa-2048-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-3072-rsa-2048-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-3072-rsa-3072-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-3072-rsa-3072-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-3072-rsa-4096-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-3072-rsa-4096-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-4096-ec-prime256v1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-4096-ec-prime256v1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-4096-ec-secp384r1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-4096-ec-secp384r1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-4096-ec-secp521r1-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-4096-ec-secp521r1-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-4096-rsa-2048-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-4096-rsa-2048-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-4096-rsa-3072-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-4096-rsa-3072-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
tlswrapper: error: no PEM secret-object in './testcerts/badkey-rsa-4096-rsa-4096-certonly.pem' 
tlswrapper: fatal: unable to obtain secret-key from the PEM file './testcerts/badkey-rsa-4096-rsa-4096-certonly.pem' 
tlswrapper: error: 0.0.0.0: SSL closed abnormally: Unsupported or invalid algorithm (ECDHE curve, signature algorithm, hash function). 
0
