badcert-ec-prime256v1-ec-prime256v1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-prime256v1-ec-prime256v1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-ec-prime256v1-extrabegin.pem' 
0
badcert-ec-prime256v1-ec-prime256v1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-prime256v1-ec-prime256v1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-ec-prime256v1-keyonly.pem' 
0
badcert-ec-prime256v1-ec-prime256v1-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-prime256v1-ec-prime256v1-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-ec-prime256v1-malformed.pem' 
0
badcert-ec-prime256v1-ec-secp224r1-unsupported.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Certificate contains unsupported features that cannot be ignored. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-ec-secp224r1-unsupported.pem' 
0
badcert-ec-prime256v1-ec-secp384r1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-prime256v1-ec-secp384r1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-ec-secp384r1-extrabegin.pem' 
0
badcert-ec-prime256v1-ec-secp384r1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-prime256v1-ec-secp384r1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-ec-secp384r1-keyonly.pem' 
0
badcert-ec-prime256v1-ec-secp384r1-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-prime256v1-ec-secp384r1-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-ec-secp384r1-malformed.pem' 
0
badcert-ec-prime256v1-ec-secp521r1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-prime256v1-ec-secp521r1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-ec-secp521r1-extrabegin.pem' 
0
badcert-ec-prime256v1-ec-secp521r1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-prime256v1-ec-secp521r1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-ec-secp521r1-keyonly.pem' 
0
badcert-ec-prime256v1-ec-secp521r1-malformed.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Invalid date/time representation. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-ec-secp521r1-malformed.pem' 
0
badcert-ec-prime256v1-rsa-2048-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-prime256v1-rsa-2048-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-rsa-2048-extrabegin.pem' 
0
badcert-ec-prime256v1-rsa-2048-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-prime256v1-rsa-2048-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-rsa-2048-keyonly.pem' 
0
badcert-ec-prime256v1-rsa-2048-malformed.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Invalid date/time representation. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-rsa-2048-malformed.pem' 
0
badcert-ec-prime256v1-rsa-3072-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-prime256v1-rsa-3072-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-rsa-3072-extrabegin.pem' 
0
badcert-ec-prime256v1-rsa-3072-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-prime256v1-rsa-3072-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-rsa-3072-keyonly.pem' 
0
badcert-ec-prime256v1-rsa-3072-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-prime256v1-rsa-3072-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-rsa-3072-malformed.pem' 
0
badcert-ec-prime256v1-rsa-4096-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-prime256v1-rsa-4096-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-rsa-4096-extrabegin.pem' 
0
badcert-ec-prime256v1-rsa-4096-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-prime256v1-rsa-4096-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-rsa-4096-keyonly.pem' 
0
badcert-ec-prime256v1-rsa-4096-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-prime256v1-rsa-4096-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-prime256v1-rsa-4096-malformed.pem' 
0
badcert-ec-secp384r1-ec-prime256v1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp384r1-ec-prime256v1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-ec-prime256v1-extrabegin.pem' 
0
badcert-ec-secp384r1-ec-prime256v1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-secp384r1-ec-prime256v1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-ec-prime256v1-keyonly.pem' 
0
badcert-ec-secp384r1-ec-prime256v1-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp384r1-ec-prime256v1-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-ec-prime256v1-malformed.pem' 
0
badcert-ec-secp384r1-ec-secp224r1-unsupported.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Certificate contains unsupported features that cannot be ignored. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-ec-secp224r1-unsupported.pem' 
0
badcert-ec-secp384r1-ec-secp384r1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp384r1-ec-secp384r1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-ec-secp384r1-extrabegin.pem' 
0
badcert-ec-secp384r1-ec-secp384r1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-secp384r1-ec-secp384r1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-ec-secp384r1-keyonly.pem' 
0
badcert-ec-secp384r1-ec-secp384r1-malformed.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Decoding error: extraneous element. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-ec-secp384r1-malformed.pem' 
0
badcert-ec-secp384r1-ec-secp521r1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp384r1-ec-secp521r1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-ec-secp521r1-extrabegin.pem' 
0
badcert-ec-secp384r1-ec-secp521r1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-secp384r1-ec-secp521r1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-ec-secp521r1-keyonly.pem' 
0
badcert-ec-secp384r1-ec-secp521r1-malformed.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Decoding error: extraneous element. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-ec-secp521r1-malformed.pem' 
0
badcert-ec-secp384r1-rsa-2048-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp384r1-rsa-2048-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-rsa-2048-extrabegin.pem' 
0
badcert-ec-secp384r1-rsa-2048-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-secp384r1-rsa-2048-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-rsa-2048-keyonly.pem' 
0
badcert-ec-secp384r1-rsa-2048-malformed.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Decoding error: extraneous element. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-rsa-2048-malformed.pem' 
0
badcert-ec-secp384r1-rsa-3072-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp384r1-rsa-3072-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-rsa-3072-extrabegin.pem' 
0
badcert-ec-secp384r1-rsa-3072-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-secp384r1-rsa-3072-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-rsa-3072-keyonly.pem' 
0
badcert-ec-secp384r1-rsa-3072-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp384r1-rsa-3072-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-rsa-3072-malformed.pem' 
0
badcert-ec-secp384r1-rsa-4096-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp384r1-rsa-4096-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-rsa-4096-extrabegin.pem' 
0
badcert-ec-secp384r1-rsa-4096-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-secp384r1-rsa-4096-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-rsa-4096-keyonly.pem' 
0
badcert-ec-secp384r1-rsa-4096-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp384r1-rsa-4096-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp384r1-rsa-4096-malformed.pem' 
0
badcert-ec-secp521r1-ec-prime256v1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp521r1-ec-prime256v1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-ec-prime256v1-extrabegin.pem' 
0
badcert-ec-secp521r1-ec-prime256v1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-secp521r1-ec-prime256v1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-ec-prime256v1-keyonly.pem' 
0
badcert-ec-secp521r1-ec-prime256v1-malformed.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Decoding error: inner element extends beyond outer element size. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-ec-prime256v1-malformed.pem' 
0
badcert-ec-secp521r1-ec-secp224r1-unsupported.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Certificate contains unsupported features that cannot be ignored. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-ec-secp224r1-unsupported.pem' 
0
badcert-ec-secp521r1-ec-secp384r1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp521r1-ec-secp384r1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-ec-secp384r1-extrabegin.pem' 
0
badcert-ec-secp521r1-ec-secp384r1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-secp521r1-ec-secp384r1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-ec-secp384r1-keyonly.pem' 
0
badcert-ec-secp521r1-ec-secp384r1-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp521r1-ec-secp384r1-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-ec-secp384r1-malformed.pem' 
0
badcert-ec-secp521r1-ec-secp521r1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp521r1-ec-secp521r1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-ec-secp521r1-extrabegin.pem' 
0
badcert-ec-secp521r1-ec-secp521r1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-secp521r1-ec-secp521r1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-ec-secp521r1-keyonly.pem' 
0
badcert-ec-secp521r1-ec-secp521r1-malformed.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Decoding error: inner element extends beyond outer element size. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-ec-secp521r1-malformed.pem' 
0
badcert-ec-secp521r1-rsa-2048-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp521r1-rsa-2048-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-rsa-2048-extrabegin.pem' 
0
badcert-ec-secp521r1-rsa-2048-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-secp521r1-rsa-2048-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-rsa-2048-keyonly.pem' 
0
badcert-ec-secp521r1-rsa-2048-malformed.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Decoding error: extraneous element. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-rsa-2048-malformed.pem' 
0
badcert-ec-secp521r1-rsa-3072-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp521r1-rsa-3072-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-rsa-3072-extrabegin.pem' 
0
badcert-ec-secp521r1-rsa-3072-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-secp521r1-rsa-3072-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-rsa-3072-keyonly.pem' 
0
badcert-ec-secp521r1-rsa-3072-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp521r1-rsa-3072-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-rsa-3072-malformed.pem' 
0
badcert-ec-secp521r1-rsa-4096-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp521r1-rsa-4096-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-rsa-4096-extrabegin.pem' 
0
badcert-ec-secp521r1-rsa-4096-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-ec-secp521r1-rsa-4096-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-rsa-4096-keyonly.pem' 
0
badcert-ec-secp521r1-rsa-4096-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-ec-secp521r1-rsa-4096-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-ec-secp521r1-rsa-4096-malformed.pem' 
0
badcert-rsa-2048-ec-prime256v1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-2048-ec-prime256v1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-ec-prime256v1-extrabegin.pem' 
0
badcert-rsa-2048-ec-prime256v1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-2048-ec-prime256v1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-ec-prime256v1-keyonly.pem' 
0
badcert-rsa-2048-ec-prime256v1-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-2048-ec-prime256v1-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-ec-prime256v1-malformed.pem' 
0
badcert-rsa-2048-ec-secp224r1-unsupported.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Certificate contains unsupported features that cannot be ignored. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-ec-secp224r1-unsupported.pem' 
0
badcert-rsa-2048-ec-secp384r1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-2048-ec-secp384r1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-ec-secp384r1-extrabegin.pem' 
0
badcert-rsa-2048-ec-secp384r1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-2048-ec-secp384r1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-ec-secp384r1-keyonly.pem' 
0
badcert-rsa-2048-ec-secp384r1-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-2048-ec-secp384r1-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-ec-secp384r1-malformed.pem' 
0
badcert-rsa-2048-ec-secp521r1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-2048-ec-secp521r1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-ec-secp521r1-extrabegin.pem' 
0
badcert-rsa-2048-ec-secp521r1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-2048-ec-secp521r1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-ec-secp521r1-keyonly.pem' 
0
badcert-rsa-2048-ec-secp521r1-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-2048-ec-secp521r1-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-ec-secp521r1-malformed.pem' 
0
badcert-rsa-2048-rsa-2048-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-2048-rsa-2048-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-rsa-2048-extrabegin.pem' 
0
badcert-rsa-2048-rsa-2048-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-2048-rsa-2048-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-rsa-2048-keyonly.pem' 
0
badcert-rsa-2048-rsa-2048-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-2048-rsa-2048-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-rsa-2048-malformed.pem' 
0
badcert-rsa-2048-rsa-3072-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-2048-rsa-3072-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-rsa-3072-extrabegin.pem' 
0
badcert-rsa-2048-rsa-3072-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-2048-rsa-3072-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-rsa-3072-keyonly.pem' 
0
badcert-rsa-2048-rsa-3072-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-2048-rsa-3072-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-rsa-3072-malformed.pem' 
0
badcert-rsa-2048-rsa-4096-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-2048-rsa-4096-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-rsa-4096-extrabegin.pem' 
0
badcert-rsa-2048-rsa-4096-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-2048-rsa-4096-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-rsa-4096-keyonly.pem' 
0
badcert-rsa-2048-rsa-4096-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-2048-rsa-4096-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-2048-rsa-4096-malformed.pem' 
0
badcert-rsa-3072-ec-prime256v1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-3072-ec-prime256v1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-ec-prime256v1-extrabegin.pem' 
0
badcert-rsa-3072-ec-prime256v1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-3072-ec-prime256v1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-ec-prime256v1-keyonly.pem' 
0
badcert-rsa-3072-ec-prime256v1-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-3072-ec-prime256v1-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-ec-prime256v1-malformed.pem' 
0
badcert-rsa-3072-ec-secp224r1-unsupported.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Certificate contains unsupported features that cannot be ignored. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-ec-secp224r1-unsupported.pem' 
0
badcert-rsa-3072-ec-secp384r1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-3072-ec-secp384r1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-ec-secp384r1-extrabegin.pem' 
0
badcert-rsa-3072-ec-secp384r1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-3072-ec-secp384r1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-ec-secp384r1-keyonly.pem' 
0
badcert-rsa-3072-ec-secp384r1-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-3072-ec-secp384r1-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-ec-secp384r1-malformed.pem' 
0
badcert-rsa-3072-ec-secp521r1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-3072-ec-secp521r1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-ec-secp521r1-extrabegin.pem' 
0
badcert-rsa-3072-ec-secp521r1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-3072-ec-secp521r1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-ec-secp521r1-keyonly.pem' 
0
badcert-rsa-3072-ec-secp521r1-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-3072-ec-secp521r1-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-ec-secp521r1-malformed.pem' 
0
badcert-rsa-3072-rsa-2048-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-3072-rsa-2048-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-rsa-2048-extrabegin.pem' 
0
badcert-rsa-3072-rsa-2048-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-3072-rsa-2048-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-rsa-2048-keyonly.pem' 
0
badcert-rsa-3072-rsa-2048-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-3072-rsa-2048-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-rsa-2048-malformed.pem' 
0
badcert-rsa-3072-rsa-3072-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-3072-rsa-3072-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-rsa-3072-extrabegin.pem' 
0
badcert-rsa-3072-rsa-3072-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-3072-rsa-3072-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-rsa-3072-keyonly.pem' 
0
badcert-rsa-3072-rsa-3072-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-3072-rsa-3072-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-rsa-3072-malformed.pem' 
0
badcert-rsa-3072-rsa-4096-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-3072-rsa-4096-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-rsa-4096-extrabegin.pem' 
0
badcert-rsa-3072-rsa-4096-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-3072-rsa-4096-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-rsa-4096-keyonly.pem' 
0
badcert-rsa-3072-rsa-4096-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-3072-rsa-4096-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-3072-rsa-4096-malformed.pem' 
0
badcert-rsa-4096-ec-prime256v1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-4096-ec-prime256v1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-ec-prime256v1-extrabegin.pem' 
0
badcert-rsa-4096-ec-prime256v1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-4096-ec-prime256v1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-ec-prime256v1-keyonly.pem' 
0
badcert-rsa-4096-ec-prime256v1-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-4096-ec-prime256v1-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-ec-prime256v1-malformed.pem' 
0
badcert-rsa-4096-ec-secp224r1-unsupported.pem
tlswrapper: error: 0.0.0.0: unable to decode public-key, err=Certificate contains unsupported features that cannot be ignored. 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-ec-secp224r1-unsupported.pem' 
0
badcert-rsa-4096-ec-secp384r1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-4096-ec-secp384r1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-ec-secp384r1-extrabegin.pem' 
0
badcert-rsa-4096-ec-secp384r1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-4096-ec-secp384r1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-ec-secp384r1-keyonly.pem' 
0
badcert-rsa-4096-ec-secp384r1-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-4096-ec-secp384r1-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-ec-secp384r1-malformed.pem' 
0
badcert-rsa-4096-ec-secp521r1-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-4096-ec-secp521r1-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-ec-secp521r1-extrabegin.pem' 
0
badcert-rsa-4096-ec-secp521r1-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-4096-ec-secp521r1-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-ec-secp521r1-keyonly.pem' 
0
badcert-rsa-4096-ec-secp521r1-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-4096-ec-secp521r1-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-ec-secp521r1-malformed.pem' 
0
badcert-rsa-4096-rsa-2048-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-4096-rsa-2048-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-rsa-2048-extrabegin.pem' 
0
badcert-rsa-4096-rsa-2048-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-4096-rsa-2048-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-rsa-2048-keyonly.pem' 
0
badcert-rsa-4096-rsa-2048-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-4096-rsa-2048-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-rsa-2048-malformed.pem' 
0
badcert-rsa-4096-rsa-3072-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-4096-rsa-3072-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-rsa-3072-extrabegin.pem' 
0
badcert-rsa-4096-rsa-3072-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-4096-rsa-3072-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-rsa-3072-keyonly.pem' 
0
badcert-rsa-4096-rsa-3072-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-4096-rsa-3072-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-rsa-3072-malformed.pem' 
0
badcert-rsa-4096-rsa-4096-extrabegin.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-4096-rsa-4096-extrabegin.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-rsa-4096-extrabegin.pem' 
0
badcert-rsa-4096-rsa-4096-keyonly.pem
tlswrapper: error: 0.0.0.0: no PEM public-object in 'testcerts/badcert-rsa-4096-rsa-4096-keyonly.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-rsa-4096-keyonly.pem' 
0
badcert-rsa-4096-rsa-4096-malformed.pem
tlswrapper: error: 0.0.0.0: malformed PEM public-object in 'testcerts/badcert-rsa-4096-rsa-4096-malformed.pem' 
tlswrapper: fatal: 0.0.0.0: unable to obtain certificate(s) from the PEM file 'testcerts/badcert-rsa-4096-rsa-4096-malformed.pem' 
0
