tlswrapper rejects fifo as a certdir
100

tlswrapper rejects fifo as a certfile
100

tlswrapper rejects fifo as a anchorfile
100

tlswrapper rejects nonexistent file as a certdir
100

tlswrapper rejects nonexistent file as a certfile
100

tlswrapper rejects nonexistent file as a anchorfile
100

tlswrapper rejects regular file as a certdir
100

tlswrapper rejects directory as a certfile
100

tlswrapper rejects directory as a anchor file
100

tlswrapper rejects link to regular file as a certdir
100

tlswrapper rejects link to directory as a certfile
100

tlswrapper rejects link to directory as a anchorfile
100

tlswrapper rejects bad min TLS version
100

tlswrapper rejects bad max TLS version
100

tlswrapper rejects bad ciphername
100

tlswrapper rejects bad ephemeral name
100

tlswrapper rejects bad proxy protocol version
100

tlswrapper rejects bad ASN.1 object
100

tlswrapper rejects zero number as a network timeout
100

tlswrapper rejects zero number as a handshake timeout
100

tlswrapper rejects negative number as a network timeout
100

tlswrapper rejects nefative number as a handshake timeout
100

tlswrapper rejects bad number as a network timeout
100

tlswrapper rejects bad numbern as a handshake timeout
100

tlswrapper rejects too large number as a network timeout
100

tlswrapper rejects too large numbern as a handshake timeout
100

